=== adrianortaaa/LLMM/XSD-1/MODULOS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="daw">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="modulo" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="descripcion" type="xs:string"/>
              <xs:element name="codigo" type="xs:positiveInteger"/>
              <xs:element name="profesor" type="xs:string"/>
              <xs:element name="fechas">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="inicio" type="tipoFecha"/>
                    <xs:element name="fin" type="tipoFecha"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="tipoFecha">
    <xs:sequence>
      <xs:element name="dia">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="mes">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="año" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== adrianortaaa/LLMM/XSD-1/MODULOS_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<daw xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:noNamespaceSchemaLocation="modulos.xsd">
  <modulo>
    <nombre>Lenguajes de marcas y sistemas de gestión de información</nombre>
    <descripcion>Estudio de XML, HTML5, CSS3 y XSD.</descripcion>
    <codigo>0373</codigo>
    <profesor>Ignacio</profesor>
    <fechas>
      <inicio>
        <dia>15</dia>
        <mes>9</mes>
        <año>2025</año>
      </inicio>
      <fin>
        <dia>22</dia>
        <mes>6</mes>
        <año>2026</año>
      </fin>
    </fechas>
  </modulo>
</daw>
