=== adrianortaaa/LLMM/DTD-ADICIONAL-2/ALUMNOS.dtd
<!ELEMENT centro_educativo (alumno*)>

<!ELEMENT alumno (nombre, apellidos, domicilio, telefono+, equipo?, aficion*, (provincia | pais), comentario?, (evaluacion, calificacion)*)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT equipo (#PCDATA)>
<!ELEMENT aficion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT comentario ANY>
<!ELEMENT evaluacion (#PCDATA)>
<!ELEMENT calificacion (#PCDATA)>

<!ATTLIST alumno
    num_alumno ID #REQUIRED
    altura_cm CDATA #IMPLIED
    sexo (hombre | mujer) #IMPLIED
    ayudado_por IDREF #IMPLIED>

<!ATTLIST telefono
    pertenece (propio | padre | madre | tutor) #REQUIRED>

=== adrianortaaa/LLMM/DTD-ADICIONAL-2/ALUMNOS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE centro_educativo SYSTEM "alumnos.dtd">
<centro_educativo>

  <alumno num_alumno="a101" altura_cm="175" sexo="hombre">
    <nombre>Marcos</nombre>
    < apellidos>García Pérez</apellidos>
    <domicilio>Calle Mayor 15, Madrid</domicilio>
    <telefono pertenece="propio">600111222</telefono>
    <telefono pertenece="padre">600333444</telefono>
    <equipo>Baloncesto</equipo>
    <aficion>Lectura</aficion>
    <aficion>Ajedrez</aficion>
    <provincia>Madrid</provincia>
    <comentario>Alumno delegado de curso.</comentario>
    <evaluacion>Primera</evaluacion>
    <calificacion>8.5</calificacion>
  </alumno>

  <alumno num_alumno="a102" ayudado_por="a101">
    <nombre>Lucía</nombre>
    <apellidos>Silva</apellidos>
    <domicilio>Av. América 4, Valencia</domicilio>
    <telefono pertenece="madre">611999888</telefono>
    <pais>España</pais>
    <comentario>
        Es nueva en el centro. Necesita apoyo en <nombre>Inglés</nombre>.
    </comentario>
    <evaluacion>Primera</evaluacion>
    <calificacion>7.0</calificacion>
    <evaluacion>Segunda</evaluacion>
    <calificacion>9.0</calificacion>
  </alumno>

</centro_educativo>
